
<<<<<<< HEAD
<<<<<<< HEAD
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  s3_host_name: <%= ENV["S3_HOST_NAME"] %>
  s3_region: <%= ENV["AWS_REGION"] %>
=======
>>>>>>> aedbc5641ed3d58c1f7a5a6c88c6f8fd7ceb96de
=======
>>>>>>> aedbc5641ed3d58c1f7a5a6c88c6f8fd7ceb96de
